Add user property for tiles to display user
neolink78/Editoria pull request #44
Opened 2024-03-15 10:58 UTC by Omcci

2024-03-20 10:26 UTC, T0MLE reviewed
CONFLIT

2024-03-22 15:04 UTC, T0MLE requested changes
C'est énervant que les likes et comments soient pas toujours alignés en fonction de la longueur du pseudo
<img width="365" alt="Capture d’écran 2024-03-22 à 16 04 10" src="https://github.com/neolink78/Editoria/assets/98027021/d5fe9b0a-05d1-4338-8f0f-2e29a1e3f393">

2024-04-07 19:01 UTC, Omcci commented
> C'est énervant que les likes et comments soient pas toujours alignés en fonction de la longueur du pseudo <img alt="Capture d’écran 2024-03-22 à 16 04 10" width="365" src="https://private-user-images.githubusercontent.com/98027021/316070273-d5fe9b0a-05d1-4338-8f0f-2e29a1e3f393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTY2ODEsIm5iZiI6MTcxMjUxNjM4MSwicGF0aCI6Ii85ODAyNzAyMS8zMTYwNzAyNzMtZDVmZTliMGEtMDVkMS00MzM4LThmMGYtMmUyOWExZTNmMzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE4NTk0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3OWNmMWMzMmVkNDdmOTllNDk5ZjFjMTI4ODVkYzFhMmM4Mjc5NDM0YjQwOWZjOTQ4NjA1ZGE3ZmUyMjBiMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FozEAVgGYYjPG-ncJNcdR9uGMwv2-kvEeNk0rrM-exs">

![Capture d’écran 2024-04-07 à 21 00 09](https://github.com/neolink78/Editoria/assets/119880787/bc1c2d19-4252-4cc9-9199-3617670c9326)
Commit : https://github.com/neolink78/Editoria/pull/44/commits/71b81812147fd52199796962e46377d59c6e96b9

2024-04-18 08:49 UTC, neolink78 approved these changes

2024-04-18 08:50 UTC, T0MLE approved these changes

2024-04-18 08:50 UTC, merged