[DashboardProjects] Add description field to project entity, add reusable components, change style in dashboard
neolink78/Editoria pull request #58
Opened 2024-04-18 23:15 UTC by Omcci

Also update pagination style, tile style and sorting projects by date of creation.

![Capture d’écran 2024-04-19 à 01 13 30](https://github.com/neolink78/Editoria/assets/119880787/e9ed41c9-b9b7-4aaa-8ba4-5fb9b3d6fef2)

2024-04-20 10:39 UTC, Omcci commented
## Page for new users
<img width="1410" alt="Capture d’écran 2024-04-20 à 12 38 13" src="https://github.com/neolink78/Editoria/assets/119880787/e16d43d4-8441-45f5-b186-74913ac0142e">

2024-04-20 13:41 UTC, Omcci commented
## Error page
![Capture d’écran 2024-04-20 à 15 40 51](https://github.com/neolink78/Editoria/assets/119880787/e0b273b5-dc10-46e4-ae23-f8d540fbdc4d)

2024-05-14 14:52 UTC, arnaudrenaud reviewed
Pour implémenter la pagination, au lieu d'avoir un état pour conserver le numéro de page, vous pouvez utiliser un paramètre d'URL (`?page=3`), ce qui permet de naviguer entre les pages avec les boutons précédent & suivant du navigateur.

2024-05-15 13:15 UTC, neolink78 requested changes
dans lib/error
les margin sont chacun dans des mesures différentes. Privilégier les vw au reste. Le  moins de px possible. 
dans lib/pagination ligne 26, mt = 8 quoi ? idem lignes 40 à 42

2024-05-15 13:42 UTC, T0MLE approved these changes

2024-05-15 13:42 UTC, neolink78 approved these changes

2024-05-15 13:42 UTC, merged